version: '1'

networks:
  myNet:
    name: myNet

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./deployment/nginx-config/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webserver-golang
      - mongo

  webserver-golang:
    container_name: webserver_golang
    build: .
    image: golang-web
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin
